# We need docker to test the packages on runtime

image: gitpod/workspace-full:latest
privileged: true
github:
  prebuilds:
    # Enable prebuilds for each push to master
    master: true
    # Used to prebuilt the workspace for merge requests
    pullRequestsFromForks: true
    addLabel: gitpod-ready
    addComment: true
tasks:
  # Fix permissions to /dev/tty required for paludis
  - before: sudo chown -R root:tty /dev/tty 
  # Start dockerd
  - before: sudo dockerd