image: 
  file: gitpod/gitpod.Dockerfile
privileged: true
github:
  prebuilds:
    # Enable prebuilds for each push to master
    master: true
# Used to prebuilt the workspace for merge requests
    pullRequestsFromForks: true
    addLabel: gitpod-ready
    addComment: true
vscode:
  extensions:
    - exiasr.hadolint@0.3.0:/FkAW3eTb+z9O7VZAyAa0w==
    - streetsidesoftware.code-spell-checker@1.9.0:zfrDgZmxZRojZW7Uky3Fww==
    - timonwong.shellcheck@0.9.0:hsU/Rd39aqPYowTqL+DbXg==