# We need docker to test the packages on runtime

image: 
  file: gitpod/gitpod.Dockerfile
privileged: true
github:
  prebuilds:
    # Enable prebuilds for each push to master
    master: true
    # Used to prebuilt the workspace for merge requests
    pullRequestsFromForks: true
    addLabel: gitpod-ready
    addComment: true
tasks:
  # Start dockerd
  - before: sudo dockerd